### ISSUE TITLE
When will this repo be merged with logstash official repo?

### ISSUE THREAD

**Issue by tbolisetty** [russorat/logstash-input-googleanalytics#1]
I see that the last update to this was 10 months ago, will this repo be merged with logstash repo in near future. And also this doesn't support for querying the real time api. Will there be any update or help provided for that.

Thanks!

**Comment by russorat** [comment]
Hi, Thanks for checking this out. Unfortunately I switched companies in early 2016 and haven't really been using Logstash since then. Right now, I don't have any plans to merge this into the logstash repo or update it to work with the realtime API. 

I would welcome a new contributor or owner for this project if you'd like to give it a shot.

**Comment by tbolisetty** [comment]
Hi,

I have made small changes to the plugin to work with realtime api. This is
my first time to fork and contribute to any open source repo, so what do
you suggest how should I proceed further.

Regards,
Tej

**Comment by russorat** [comment]
i believe you should be able to open a PR and request a merge from your fork to mine. These instructions might help: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Also, this would be the first time i've ever had someone contribute so it's a learning process all around :)

**Comment by russorat** [comment]
Fixed here: https://github.com/russorat/logstash-input-googleanalytics/pull/2

**Comment by russorat** [comment]
Thanks for your contribution!
